version: '3.8'

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dealership-scraper
    volumes:
      - scraper-data:/app/output
      - scraper-logs:/app/logs
    environment:
      - TZ=America/Chicago
      - HEADLESS=true
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SCRAPE_INTERVAL=${SCRAPE_INTERVAL:-3600}
    restart: unless-stopped
    networks:
      - dokploy-network
    mem_limit: 2g
    mem_reservation: 1g
    cpus: '1.5'

volumes:
  scraper-data:
    driver: local
  scraper-logs:
    driver: local

networks:
  dokploy-network:
    external: true
